#!/usr/bin/env bash

AUTOINIT_D="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"


__autoinit_tldr_init() {
    "${AUTOINIT_D}/autoinit-asdf-plugin" "tldr" "init"
}


__autoinit_tldr_install() {
    "${AUTOINIT_D}/autoinit-asdf-plugin" "tldr" "install"
    if [[ $? -eq 0 ]]; then
        __autoinit_tldr_configure
    else
        __autoinit_warn "Failed to install tldr, cannot automatically configure tldr"
    fi
}

__autoinit_tldr_autorun() {
    shift
    local argv="$@"


    if ! "${AUTOINIT_D}/autoinit-asdf-plugin" "tldr" is-installed; then
        "${AUTOINIT_D}/autoinit-asdf-plugin" "tldr" "autoload"
        eval "$(__autoinit_tldr_init)"
        __autoinit_tldr_configure
    else
        "${AUTOINIT_D}/autoinit-asdf-plugin" "tldr" "autoload"
        eval "$(__autoinit_tldr_init)"
    fi

    $argv
}

__autoinit_tldr_configure() {
    case "$(uname)" in
        Darwin)
            readonly _STAT_MODIFIED_FMT="-f %m"
            ;;

        Linux)
            readonly _STAT_MODIFIED_FMT="--format %Y"
            ;;
        *)
            echo "Error: unknown platform $(uname), cannot determine file stat format" 1>&2
            exit
            ;;
    esac
    tldr --update
}

main() {
    local cmd="$1"
    shift
    local argv="$@"

    # There are multiple entrypoints that may call plugin installation - and in specific the
    # `autorun` command will trigger an install. We set this globally to handle this path.
    # This seems like a code smell.
    export ASDF_REPOSITORY="https://github.com/adrienthebo/asdf-tealdeer"

    case "$cmd" in
        install)
            __autoinit_tldr_install
            ;;

        autorun)
            __autoinit_tldr_autorun "$@"
            ;;

        configure)
            __autoinit_tldr_configure
            ;;

        *)
            "${AUTOINIT_D}/autoinit-asdf-plugin" "tldr" "$cmd" $argv
            ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    # shellcheck disable=SC2068
    main $@
fi