#!/usr/bin/env bash

AUTOINIT_D="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
__LIBDIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")"
source "${__LIBDIR}/colors.sh"
source "${__LIBDIR}/autoinit.sh"


__autoinit_az_init() {
    __autoinit_error "autoinit-az/init: not implemented"
    return 1
}


__autoinit_az_configure() {
    declare -a azure_sp_vars=(AZURE_CLIENT_ID AZURE_CLIENT_SECRET AZURE_TENANT_ID)
    local missing_sp_vars=false

    az config set core.collect_telemetry=no
    az config set core.output=table

    if [[ -n $AZURE_RESOURCE_GROUP ]]; then
        __autoinit_notice "autoinit-az/configure: setting default resource group to '$AZURE_RESOURCE_GROUP'"
        az config set defaults.group="$AZURE_RESOURCE_GROUP"
    fi

    for v in "${azure_sp_vars[@]}"; do
        if [[ -z "${!v}" ]]; then
            __autoinit_warn "autoinit-az/configure: missing Azure service principal variable '$v'"
            missing_sp_vars=true
        fi
    done

    if [[ $missing_sp_vars = true ]]; then
        __autoinit_error "autoinit-az/configure: one or more Azure service principal variables are absent. Set those variables and re-run configuration."
        return 1
    else
        az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
    fi
}


__autoinit_az_describe() {
    cat - <<EOD
# autoinit-az

> Install and configure the Azure CLI.
> More information: <https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest>.

Environment variables:
    - SDK:
        - General SDK Configuration:
            - AZURE_SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID}"
            - AZURE_RESOURCE_GROUP="${AZURE_RESOURCE_GROUP}"
            - AZURE_CONFIG_DIR="${AZURE_CONFIG_DIR}"
        - Identity:
            - AZURE_CLIENT_ID="${AZURE_CLIENT_ID}"
            - AZURE_CLIENT_SECRET="${AZURE_CLIENT_SECRET}"
            - AZURE_TENANT_ID="${AZURE_TENANT_ID}"
    - Terraform:
        - ARM_SUBSCRIPTION_ID="${ARM_SUBSCRIPTION_ID}"
        - ARM_TENANT_ID="${ARM_TENANT_ID}"
        - ARM_CLIENT_ID="${ARM_CLIENT_ID}"
        - ARM_CLIENT_SECRET="${ARM_CLIENT_SECRET}"

Documentation:
    - [Azure SDK environment variables](https://github.com/Azure/azure-sdk/blob/main/_includes/tables/environment_variables.md)
    - [Azure Terraform provider variables](https://docs.microsoft.com/en-us/azure/developer/terraform/authenticate-to-azure?tabs=bash)
EOD
}


main() {
    local cmd="$1"

    case "$cmd" in
        init)
            __autoinit_az_init
            ;;

        configure)
            __autoinit_az_configure
            ;;

        describe)
            __autoinit_az_describe
            ;;

        *)
            __autoinit_error "autoinit-az/${cmd}: not implemented"
            return 1
            ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    # shellcheck disable=SC2068
    main $@
fi