#!/usr/bin/env bash

AUTOINIT_D="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"


__autoinit_tldr_init() {
    "${AUTOINIT_D}/autoinit-asdf-plugin" "tldr" "init"
    echo "tldr --update"
}


main() {
    local cmd="$1"
    
    case "$cmd" in
        init)
            __autoinit_tldr_init
            ;;
            
        install)
            ASDF_REPOSITORY="https://github.com/adrienthebo/asdf-tealdeer" "${AUTOINIT_D}/autoinit-asdf-plugin" "tldr" "install"
            ;;
            
        *)
            "${AUTOINIT_D}/autoinit-asdf-plugin" "tldr" $@
            ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    # shellcheck disable=SC2068
    main $@
fi