#!/usr/bin/env bash

AUTOINIT_D="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"


__autoinit_direnv_init() {
    "${AUTOINIT_D}/autoinit-asdf-plugin" "direnv" "init"
    echo 'eval "$(direnv hook "$(basename "$SHELL")")"'
}


main() {
    local cmd="$1"
    
    case "$cmd" in
        init)
            __autoinit_direnv_init 
            ;;
            
        *)
            "${AUTOINIT_D}/autoinit-asdf-plugin" "direnv" $@
            ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    # shellcheck disable=SC2068
    main $@
fi