#!/usr/bin/env bash

AUTOINIT_D="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
__LIBDIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")"
source "${__LIBDIR}/colors.sh"
source "${__LIBDIR}/autoinit.sh"


__autoinit_aws_init() {
    "${AUTOINIT_D}/autoinit-asdf-plugin" "awscli" "init"
    if [[ $? -eq 0 ]]; then
        cat - <<EOD
complete -C "$(asdf which aws_completer)" aws
EOD
    else
        cat - <<EOD
if command -v aws_completer 1>/dev/null; then
    echo "aws_completer is available (even though awscli isn't available), initializing completion"
    complete -C "$(which aws_completer)" aws
fi
EOD
    fi
}


__autoinit_aws_configure() {
    local aws_var aws_vars

    aws_vars=(AWS_SSO_URL AWS_SSO_REGION AWS_ACCOUNT_ID AWS_ROLE_NAME AWS_REGION)

    for aws_var in "${aws_vars[@]}"; do
        if [[ -z "${!aws_var}" ]]; then
            __autoinit_warn "Error: AWS variable \"$aws_var\" is unset"
            local aws_var_unset=true
        fi
    done

    if ! [[ -z "$aws_var_unset" ]]; then
        local script=$(realpath "$0")
        __autoinit_warn "AWS Variables are not set, skipping autoconfig of files."
        __autoinit_warn "Re-run ${script} when AWS_ variables are set"
        return 1
    fi

    __autoinit_debug "$(color blue "autoinit-aws: Forcing AWS config to just use SSO credentials")"



    config_file="${AWS_CONFIG_FILE:-$HOME/.aws/config}"
    config_dir="$(dirname "$config_file")"

    [[ -d "$config_dir" ]] || mkdir "$config_dir"
    cat <<- AWSFILE > "$config_file"
[default]
sso_start_url = ${AWS_SSO_URL}
sso_region = ${AWS_SSO_REGION}
sso_account_id = ${AWS_ACCOUNT_ID}
sso_role_name = ${AWS_ROLE_NAME}
region = ${AWS_REGION}
AWSFILE

    # update docker config to use ecr-login
    # if we don't have a .docker/config.json, create:

    if [ ! -d /home/gitpod/.docker ]; then
        mkdir -p /home/gitpod/.docker && echo '{}' > /home/gitpod/.docker/config.json
    elif [ ! -f /home/gitpod/.docker/config.json ]; then
        echo '{}' > /home/gitpod/.docker/config.json
    fi

    __autoinit_debug "autoinit-aws: Ensuring Docker Config uses ecr-login for ECR repositories"

    cp /home/gitpod/.docker/config.json /home/gitpod/.docker/config_bak.json
    jq '.credHelpers["public.ecr.aws"]="ecr-login"' /home/gitpod/.docker/config.json > /home/gitpod/.docker/config_tmp.json
    jq ".credHelpers[\"${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com\"]=\"ecr-login\"" /home/gitpod/.docker/config_tmp.json > /home/gitpod/.docker/config.json
    rm /home/gitpod/.docker/config_tmp.json

    echo "$(color blue "autoinit-aws: Start an AWS SSO login session")"

    if aws sts get-caller-identity 1>/dev/null 2>/dev/null; then
        echo "$(color blue "autoinit-aws: AWS credentials already loaded, run 'aws sso login' to re-authenticate")"
    else
        BROWSER="/ide/bin/helpers/browser.sh" aws sso login
        if [[ $? -ne 0 ]]; then
            __autoinit_warn "autoinit-aws: SSO login failed - finishing aws configuration early"
            return 1
        else
            PAGER=/bin/cat aws sts get-caller-identity
        fi
    fi

    if [[ -n $EKS_CLUSTER ]]; then
        echo "$(color blue "autoinit-aws: load kubectl configuration for $EKS_CLUSTER")"
        aws eks update-kubeconfig --name "$EKS_CLUSTER"
    fi
}


__autoinit_aws_describe() {
    cat - <<EOD
Configure awscliv2, load AWS credentials, and configure EKS kubectl credentials.

Environment variables:
    - awscli:
        - AWS_CONFIG_FILE="${AWS_CONFIG_FILE}"
        - AWS_SHARED_CREDENTIALS_FILE="${AWS_SHARED_CREDENTIALS_FILE}"
    - API access (used with 'aws sso login'):
        - AWS_SSO_URL="${AWS_SSO_URL}"
        - AWS_SSO_REGION="${AWS_SSO_REGION}"
        - AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID}"
        - AWS_ROLE_NAME="${AWS_ROLE_NAME}"
        - AWS_REGION="${AWS_REGION}"
    - EKS (used with 'aws eks update-kubeconfig'):
        - EKS_CLUSTER="${EKS_CLUSTER}"
EOD
}


main() {
    local cmd="$1"

    case "$cmd" in
        init)
            __autoinit_aws_init
            ;;
        configure)
            __autoinit_aws_configure
            ;;

        describe)
            __autoinit_aws_describe
            ;;

        autoload)
            "${AUTOINIT_D}/autoinit-asdf-plugin" "awscli" autoload
            ;;

        is-shadowed)
            "${AUTOINIT_D}/autoinit-asdf-plugin" "awscli" is-shadowed "aws"
            ;;

        *)
            "${AUTOINIT_D}/autoinit-asdf-plugin" "awscli" $@
            ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    # shellcheck disable=SC2068
    main $@
fi