#!/usr/bin/env bash

AUTOINIT_D="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"


__autoinit_bat_init() {
    "${AUTOINIT_D}/autoinit-asdf-plugin" "bat" "init"
    local bat_dir="$(realpath "$(dirname "$(asdf which bat)")/../")"
    local autocomplete="${bat_dir}/autocomplete/bat.$(basename "$SHELL")" 
    echo "source \"$autocomplete\""
}


main() {
    local cmd="$1"
    
    case "$cmd" in
        init)
            __autoinit_bat_init 
            ;;
            
        *)
            "${AUTOINIT_D}/autoinit-asdf-plugin" "bat" $@
            ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    # shellcheck disable=SC2068
    main $@
fi