#!/usr/bin/env bash

AUTOINIT_D="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"


main() {
    "${AUTOINIT_D}/autoinit-asdf-plugin" "kubectl-kots" $@
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    # shellcheck disable=SC2068
    main $@
fi