version: 1.1.0
config:
  style:
    # The theme defines the terminal colors used by Snipkit.
    # Available themes:default(.light|.dark),simple.
    theme: default
  # Your preferred editor to open the config file when typing 'snipkit config edit'.
  editor: "" # Defaults to a reasonable value for your operation system when empty.
  # The command which should run if you don't provide any subcommand.
  defaultRootCommand: "" # If not set, the help text will be shown.
  scripts:
    # The path to the shell to execute scripts with. If not set or empty, $SHELL will be used instead. Fallback is '/bin/bash'.
    shell: ""
    # Defines how parameters are handled. Allowed values: SET (sets the parameter value as shell variable) and REPLACE (replaces all occurrences of the variable with the actual value)
    parameterMode: ""
    # If set to true, any comments in your scripts will be removed upon executing or printing.
    removeComments: false
  manager:
    fsLibrary:
      # If set to false, the files specified via libraryPath will not be provided to you.
      enabled: true
      # Paths directories that hold snippets files. Each file must hold one snippet only.
      libraryPath:
        - /home/gitpod/.dotfiles/snippets
      # Only files with endings which match one of the listed suffixes will be considered.
      # If set to true, the files will not be parsed in advance. This means, only the filename can be used as the snippet name.
      lazyOpen: false
      # If set to true, the title comment will not be shown in the preview window.
      hideTitleInPreview: true