#!/usr/bin/env bash

set -x

PROJECT_ROOT="$(dirname $(dirname "$0"))"

echo "Project root: $PROJECT_ROOT"

for script in $PROJECT_ROOT/script.d/*.sh; do
  $script
done

for script in $PROJECT_ROOT/bash.d/*.sh; do
  cp $script ~/.bashrc.d/
end
