#!/usr/bin/env bash

PROJECT_ROOT="$(realpath $(dirname $(dirname "${BASH_SOURCE[0]}")))"

echo "Project root: $PROJECT_ROOT"

for script in $PROJECT_ROOT/script.d/*.sh; do
  echo "Running setup script $script"
  $script
done

for script in $PROJECT_ROOT/bashrc.d/*.sh; do
  echo "Copying bashrc $script to $HOME/.bashrc.d/"
  cp $script ~/.bashrc.d/
done

[[ -d "$HOME/.local/bin" ]] || mkdir -p "$HOME/.local/bin"
for executable in $PROJECT_ROOT/bin/*; do
  cp $executable "$HOME/.local/bin/"
done