#!/usr/bin/env bash

PROJECT_ROOT="$(realpath $(dirname $(dirname "${BASH_SOURCE[0]}")))"

echo "Project root: $PROJECT_ROOT"

if [[ -d "/home/linuxbrew" ]]; then
  echo "Loading linuxbrew shellenv"
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

if ! command -v brew 1>/dev/null 2>/dev/null; then
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  sudo chown gitpod:gitpod "$HOME/.bash_profile"
  echo '# Set PATH, MANPATH, etc., for Homebrew.' >> "$HOME/.bash_profile"
  echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> "$HOME/.bash_profile"
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

brew install chezmoi

# To reduce the number of repositories and round trips we use ~/.dotfiles as the chezmoi
# source; using the default source will add a second repository that needs to be cloned.
# On the first invocations of chezmoi this alternate source path needs to be specified
# for init and apply; the `chezmoi apply` will create `~/.config/chezmoi/chezmoi.toml`
# which will persist the sourceDir in subsequent invocations.
chezmoi --source $HOME/.dotfiles init $HOME/.dotfiles
chezmoi --source $HOME/.dotfiles apply -v

for script in $PROJECT_ROOT/script.d/*.sh; do
  echo "Running setup script $script"
  $script
done